Revert "[review] ensure_future decorator"
This reverts commit 9880de0440fd21690e65d5f9d01169d0f8fbaa41.

RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_5'.