Aio monitor (#3788)
Migrate golem monitor client to asyncio.

* Squashed commit of the following:

[...]

commit 121d9b06b8e43aef5b833560ae2f0edfe4cfb925
Author: Dariusz Rybi <dariusz@golem.network>
Date:   Thu Jan 10 13:10:59 2019 +0100

    Update docker tests

commit cb40113bf9e2d0fc6ca9cbe50aa8e9d553581560
Author: Dariusz Rybi <dariusz@golem.network>
Date:   Thu Jan 10 12:36:32 2019 +0100

    Update golemapp tests

commit 4933aa548c5a2d7e3386b596d84f5812b0d23924
Author: Dariusz Rybi <dariusz@golem.network>
Date:   Thu Jan 10 12:07:32 2019 +0100

    Update node tests

commit 7b11e075066147a5fadab08659b83a7152cc2a17
Author: Dariusz Rybi <dariusz@golem.network>
Date:   Thu Jan 10 10:57:15 2019 +0100

    Sometimes global is expected

commit e71095afd2bb7022d3bb984504a61b78a5b6aaea
Author: Dariusz Rybi <jiivanq@gmail.com>
Date:   Mon Jan 7 23:43:28 2019 +0100

    Twisted and asyncio in a single app

* Migrate monitor to asyncio

* Asynchronize aio tasks

* Update tests

* Catch main event loop exceptions

* [review] Type hints and function names

* [review] remove duplicate of .assertAddSystemEvent(reactor)

* Reintroduce thread queue type hint

* WIP

* [WIP] Monitor with new aio approach

* Remove unnecessary change in docker tests

* Fix tests

* Clean golem_async

* lints

* eventloop

* [review] Clean up SENDER_THREAD_TIMEOUT

* Remove unused @locked decorator

* [review] ensure_future decorator

* Revert "[review] ensure_future decorator"

This reverts commit 9880de0440fd21690e65d5f9d01169d0f8fbaa41.

RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_5'.

* Rename run_at_most_every to throttled